#!/bin/sh

CC="gcc"

while true; do
	case $1 in
		-CC)
			CC="$2"
			shift 2
			;;
		-CFLAGS)
			CFLAGS="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

make generator > /dev/null || exit 1

./compile $@ > /tmp/stac.$$.c || exit 1

${CC} /tmp/stac.$$.c -o /tmp/stac.$$ -Iinclude -I. \
	${CFLAGS} \
	util.o assemble.o str.o libstac/libstac.o || {
	rm /tmp/stac.$$.c
	exit 1
}
rm /tmp/stac.$$.c

/tmp/stac.$$
rm /tmp/stac.$$
